### ISSUE TITLE
Can't run it in Win 10 / Visual Studio 2019 

### ISSUE THREAD

**Issue by gramagrass** [runwayml/ofxRunway#11]
Error in this preprocessor command:
```
#if (OFX_NETWORKUTILS_VERSION_MAJOR > OF_VERSION_MAJOR || OFX_NETWORKUTILS_VERSION_MINOR > OF_VERSION_MINOR)
    #warning Your version of openFrameworks may be too old for this addon.
    #warning Please try the stable branch of this addon or see the README.md for more info.
#elif (OFX_NETWORKUTILS_VERSION_MAJOR < OF_VERSION_MAJOR || OFX_NETWORKUTILS_VERSION_MINOR < OF_VERSION_MINOR)
    #warning Your version of openFrameworks may be too new for this addon.
    #warning Please try the stable branch of this addon or see the README.md for more info.
#endif

```

Debug log:

```
1>------ Build started: Project: example-GPT-2, Configuration: Debug x64 ------
1>ofxNetworkUtils.cpp
1>C:\of\addons\ofxNetworkUtils\src\ofxNetworkUtils.cpp(16,1): fatal error C1021: invalid preprocessor command 'warning'
1>Done building project "example-GPT-2.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

**Comment by roymacdonald** [comment]
Hi!! Thanks for letting me know. I am developing on macos and as I have not finished this addon yet I have not tested it on any other platform. 
That error seems to be related to an addon used. maybe @bakercp can give us a clue. 
On the meanwhile it seems like it could be possible to comment out the lines that are bothering, those starting with `#warning`. 
I'll give it a test on windows tomorrow and let you know.

**Comment by carlesgutierrez** [comment]
I had this error too with Visual2017 using OF 0.11.0. I've commented those lines, now compiles and run.
At least for the example-MaskRCNN says "**connected to Runway** but no data receiving back".
Edit: After some tests now I've get both apps synchronized and working receiving Image and Data both. First open OF app, then open RunWayML with the right model and wait.

**Comment by roymacdonald** [comment]
Hey @carlesgutierrez I have not tested it on windows but if it compiles it should work.
Usually I'll have RunwayML constantly open and running, then when opening the OF app it should connect. It really should not matter as eventually these should connect. In any case, enabling the verbose log using `ofSetLogLevel(OF_LOG_VERBOSE);` in `ofApp::setup`will give you a lot more info. I'll add a warning in the readme pointing out this issue on windows. That addon should get an update too.

**Comment by bakercp** [comment]
I just got rid of this warning.  Perhaps pull the latest version of ofxNetworkUtils?

**Comment by roymacdonald** [comment]
Awesome! thanks @bakercp ! 
I'll close this issue.
