### ISSUE TITLE
Help with PoseNet example

### ISSUE THREAD

**Issue by tobyshooters** [runwayml/ofxRunway#7]
I'm trying to setup a PoseNet example. I want to receive the pose coordinates from Runway's PoseNet model and stream them to OpenFrameworks.

Is there a difference between using `ofxRunway` via http or just `ofxOsc` directly?
I couldn't get the latter to work, and for the former I'm getting the OAuth error below.

`make[1]: *** [/Users/cristobalsciutto/dev/openframework/addons/obj/osx/Release/ofxHTTP/libs/ofxHTTP/src/OAuth10Credentials.o] Error 1`

The code is quite simple:
```
void ofApp::setup() {
    runway.setup(this, "https://localhost:8000");
    runway.start();
}

void ofApp::update() {
    ofxRunwayData d;
    if (runway.tryReceive(d)) {
        cout << d.data << endl;
    }
}
```

This should be quite simple, but I'm struggling to find documentation.
I feel like this *the* basic example...

Thanks for any help!

**Comment by roymacdonald** [comment]
Hi Cristobal. I have not implemented the PoseNet data parsing yet, I should have it on the following weeks.
As of the example, yes, that's like a super basic and I have never seen that error. 
It looks like you are getting that error during compilation not during runtime. Which OS are you using? I have only tested it on macos.
Edit:
Sorry, I see from the route of your error that you are on `osx`. If you are setting this from scratch make sure to do so using the project generator and remember to include ofxPoco as one of the needed addons.

**Comment by roymacdonald** [comment]
Try to avoid osc, as runwayml does not have it implemented correctly, and it might be removed in the future. 
HTTP is the main protocol that RunwayML uses, thus it is the most robust.

**Comment by tobyshooters** [comment]
This was the error: https://github.com/bakercp/ofxHTTP/issues/51
Fixed by commenting out code, rather than the json.hpp fix mentioned

**Comment by tobyshooters** [comment]
I'm getting a linker error related to `getCaptions`. Any suggestions?

```
Undefined symbols for architecture x86_64:
  "ofxRunwayData::getCaptions(std::__1::vector<ofxRunwayCaption, std::__1::allocator<ofxRunwayCaption> >&, float, float)", referenced from:
      ofxRunway::get(std::__1::vector<ofxRunwayCaption, std::__1::allocator<ofxRunwayCaption> >&, float, float) in ofxRunway.o
  "ofxRunwayData::getImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ofPixels_<unsigned char>&)", referenced from:
      ofxRunway::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ofPixels_<unsigned char>&) in ofxRunway.o
  "ofxRunwayData::setImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ofPixels_<unsigned char> const&, ofxRunwayImageType, int, int)", referenced from:
      ofxRunway::send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ofPixels_<unsigned char> const&, ofxRunwayImageType, int, int) in ofxRunway.o
  "ofxRunwayData::getString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)", referenced from:
      ofxRunway::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in ofxRunway.o
  "ofxRunwayData::setString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      ofxRunway::send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in ofxRunway.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/009_runway] Error 1
make: *** [Release] Error 2
```

**Comment by roymacdonald** [comment]
Good to know you found the other error.
can you compile the other examples?
Is the file ofxRunwayData.cpp in your Xcode project? as in the following screenshot :
<img width="263" alt="Screen Shot 2019-12-16 at 23 04 53" src="https://user-images.githubusercontent.com/974878/70964078-85aade00-2058-11ea-9dc5-1c0bb8300fd9.png">

You get this error when you have a function defined (usually in an `.h`) but you don't have the implementation of it being compiled (what's in the `cpp` file)

**Comment by tobyshooters** [comment]
Yup, I directly cloned the repo into `openframework/addons`
```
➜  openframework tree -I "example*" addons/ofxRunway
addons/ofxRunway
├── README.md
├── addon_config.mk
├── assets
│   ├── appScreenshot.jpg
│   └── cover_runway_openframeworks_github.jpg
└── src
    ├── ofxRunway.cpp
    ├── ofxRunway.h
    ├── ofxRunwayData.cpp
    ├── ofxRunwayData.h
    └── ofxRunwayModelUtils.h
```


[Edit: fixed by changing the `realpath` in the makefile]
<del>As for the other examples, I was not sure how to compile them. I copied one over to `apps/myApps`, then dragged it into the projectGenerator, but got: </del>
```
Makefile:13: //libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk: No such file or directory
make: *** No rule to make target `//libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk'.  Stop.
```

**Comment by roymacdonald** [comment]
what are you using for compiling? make?
for the other examples, just drag the example's folder onto project generator and generate.

**Comment by tobyshooters** [comment]
Compiled the example, and got the similar error:
```
Undefined symbols for architecture x86_64:
  "ofxRunwayData::setBoolean(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)", referenced from:
      ofApp::update() in ofApp.o
  "ofxRunwayData::getCaptions(std::__1::vector<ofxRunwayCaption, std::__1::allocator<ofxRunwayCaption> >&, float, float)", referenced from:
      ofxRunway::get(std::__1::vector<ofxRunwayCaption, std::__1::allocator<ofxRunwayCaption> >&, float, float) in ofxRunway.o
  "ofxRunwayData::getImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ofPixels_<unsigned char>&)", referenced from:
      ofxRunway::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ofPixels_<unsigned char>&) in ofxRunway.o
  "ofxRunwayData::setFloat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, float)", referenced from:
      ofApp::update() in ofApp.o
  "ofxRunwayData::setImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ofBaseHasPixels_<unsigned char> const&, ofxRunwayImageType, int, int)", referenced from:
      ofApp::update() in ofApp.o
  "ofxRunwayData::setImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ofPixels_<unsigned char> const&, ofxRunwayImageType, int, int)", referenced from:
      ofxRunway::send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ofPixels_<unsigned char> const&, ofxRunwayImageType, int, int) in ofxRunway.o
  "ofxRunwayData::getString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)", referenced from:
      ofxRunway::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in ofxRunway.o
  "ofxRunwayData::setString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      ofxRunway::send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in ofxRunway.o
ld: symbol(s) not found for architecture x86_64
```

I'm just using `make`.

**Comment by roymacdonald** [comment]
Are you able to compile the basic OF examples  using `make`? 
I think that there is some missing lines in the addon_config file. Let me check.

**Comment by tobyshooters** [comment]
Yeah, my non-Runway related apps work compile fine.

**Comment by roymacdonald** [comment]
ok. so I found that in the `addon_config.mk`there were missing some things. ~~I already fixed this issue. Please update to the newest version of ofxRunway.~~
edit: I am getting errors while compiling. I'll get into this tomorrow.

**Comment by brannondorsey** [comment]
Not sure about the compile errors, and I haven't run this myself, but at first glance the `https://localhost:8000` should be switched to `http://localhost:8000`. HTTP network integrations on localhost expect to speak HTTP, not HTTPS. So once you get this compiling, you'll want to change that as well.

**Comment by roymacdonald** [comment]
Thanks @brannondorsey, all the provided examples use `http`.
The problem now seems to be to compile with `make`. I'll figure this out and make the necesary fixes.

**Comment by roymacdonald** [comment]
@tobyshooters can you try to compile using xcode instead of make? I get a lot of compilation errors by trying to compile some ofxHTTP examples. I think it has to do with a much larger problem regarding make and addons.

**Comment by tobyshooters** [comment]
Thanks for the update. I'm getting errors relating to `json.hpp` on both my own app and on the `ofxRunway` examples. I'm investigating...

<img width="554" alt="Screen Shot 2019-12-18 at 10 06 57 AM" src="https://user-images.githubusercontent.com/48459292/71097565-28a94800-217e-11ea-99fe-de37c78b240a.png">

**Comment by roymacdonald** [comment]
thats odd. which version of openFrameworks are you using? can you try with the latest nightly build? these are in openframeworks.cc/download if you scroll a bit down you'll find em.
as well,  which line(s) in ofxRunwayData.cpp are triggering this error?

**Comment by roymacdonald** [comment]
Sorry, I made a mistake with my last push. I've reverted it. Please update from what I just pushed to this repo. Now it compiles again with xcode. My apologies.

**Comment by roymacdonald** [comment]
so, there is a bug in openFrameworks when it parses the addon files. I'll post an issue about it.
I've just added the whole implementation for PoseNet and and an example for it

**Comment by cyrstem** [comment]
hey  im trying to compile this esxample but i get this  errors
`
/home/jacos/OF/libs/glm/include/glm/detail/type_vec4.hpp:19:9: note: ‘glm::i16vec4’ {aka ‘struct glm::tvec4<short int, glm::packed_highp>’} declared here
   19 |  struct tvec4
      |         ^~~~~
/home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp: In member function ‘bool ofxRunwayData::checkSetData(const string&, const string&)’:
**/home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp:13:10: error: ‘using ofJson = using json = class nlohmann::basic_json<>’ {aka ‘class nlohmann::basic_json<>’} has no member named ‘contains’
   13 |  if(data.contains(name)){
      |          ^~~~~~~~**
/home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp: In member function ‘void ofxRunwayData::setImage(const string&, const ofPixels&, ofxRunwayImageType, int, int)’:
/home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp:39:11: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
   39 |     width < pixelsToReceive.getWidth() &&
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp:40:12: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
   40 |     height < pixelsToReceive.getHeight()){
      |     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp: In member function ‘bool ofxRunwayData::getImage(const string&, ofPixels&)’:
**/home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp:118:11: error: ‘using ofJson = using json = class nlohmann::basic_json<>’ {aka ‘class nlohmann::basic_json<>’} has no member named ‘contains’
  118 |  if(!data.contains(name)){
      |           ^~~~~~~~**
/home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp: In member function ‘bool ofxRunwayData::getData(const string&, const std::vector<std::__cxx11::basic_string<char> >&, T&, bool)’:
/home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp:143:11: error: ‘using ofJson = using json = class nlohmann::basic_json<>’ {aka ‘class nlohmann::basic_json<>’} has no member named ‘contains’
  143 |  if(!data.contains(name)){
      |           ^~~~~~~~
/home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp: In member function ‘bool ofxRunwayData::getDataArray(const string&, const std::vector<std::__cxx11::basic_string<char> >&, std::vector<T>&)’:
**/home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp:175:11: error: ‘using ofJson = using json = class nlohmann::basic_json<>’ {aka ‘class nlohmann::basic_json<>’} has no member named ‘contains’
  175 |  if(!data.contains(name)){
      |           ^~~~~~~~**

- /home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp: In member function ‘bool ofxRunwayData::getCaptions(std::vector<ofxRunwayCaption>&, float, float, ofxRunwayCaptionType)’:
- /home/jacos/OF/addons/ofxRunway/src/ofxRunwayData.cpp:255:22: warning: comparison of integer expressions of different signedness: ‘int’ and ‘nlohmann::basic_json<>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
-   255 |    for(int i = 0 ; i < boxes.size(); i++){
-       |                    ~~^~~~~~~~~~~~~~
- make[1]: *** 

[/home/jacos/OF/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:354: **

- /home/jacos/OF/addons/obj/linux64/Release/ofxRunway/src/ofxRunwayData.o] Error 1
- make[1]: Leaving directory '/home/jacos/OF/addons/ofxRunway/example-PoseNet'
- make: *** [/home/jacos/OF/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2
- `

**

**Comment by roymacdonald** [comment]
HI! I have not tested it on Linux but it seem that for some reason ofJson's function `contains(std::string )` is not working for you. ofJson is actually just a typedef for [nlohmann::json](https://github.com/nlohmann/json) 
Seems to be related to the original issue where make is bothering. can you update the example using project generator and then try and build again?

**Comment by johanjohan** [comment]
I remember that happened to me as well on Win10. I replaced json.hpp in the OF lib 0.11. with the newest version from the author https://github.com/nlohmann/json/tree/develop/single_include/nlohmann

**Comment by cyrstem** [comment]
> HI! I have not tested it on Linux but it seem that for some reason ofJson's function `contains(std::string )` is not working for you. ofJson is actually just a typedef for [nlohmann::json](https://github.com/nlohmann/json)
> Seems to be related to the original issue where make is bothering. can you update the example using project generator and then try and build again?

hey so  for somereason   when i do the update the makefile doesnt create correctly i copy and paste the make file from other project and it  gets me previews error. i try on my mac  and get this errors :
`/Users/jacos/of_v0.10.1_osx_release/addons/ofxRunway/src/ofxRunwayData.cpp:13:10: No member named 'contains' in 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>'
/Users/jacos/of_v0.10.1_osx_release/addons/ofxRunway/src/ofxRunwayData.cpp:118:11: No member named 'contains' in 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>'
/Users/jacos/of_v0.10.1_osx_release/addons/ofxRunway/src/ofxRunwayData.cpp:143:11: No member named 'contains' in 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>'
/Users/jacos/of_v0.10.1_osx_release/addons/ofxRunway/src/ofxRunwayData.cpp:175:11: No member named 'contains' in 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>'`
 its seems to be the same   gona try  johanjohan  fix later today

**Comment by roymacdonald** [comment]
Hi @cyrstem , this is really odd. Are you using `make` as well on the mac?

**Comment by roymacdonald** [comment]
btw, @cyrstem which OF version are you using? it should be the newest one,

**Comment by roymacdonald** [comment]
I have just build it on macos 10.14.6 using make and it works

**Comment by cyrstem** [comment]
nope im using xcode to compile but i  was using of_v0.10.1_osx_release on this mac

**Comment by roymacdonald** [comment]
@cyrstem did you got it to work?

**Comment by cyrstem** [comment]
@roymacdonald  Yes in mac  it work  on the new OF  im updating the linux OF to see if that works.

**Comment by roymacdonald** [comment]
glad to know. Please let me know if it works on Linux. I am adding some CI for all platforms.

**Comment by cyrstem** [comment]
So, this happens on linux when trying to compile unde OF 11  for  some reason when drag and drop 
 the examples to the project manager the make file is not generated correctly, i copy the  make file from other project and it works fine 

```
addons/ofxRunway/example-PoseNet  master ✗                                                   4d ⚑ ◒  ⍉
▶ make
Makefile:13: /home/jacos/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk: No such file or directory
make: *** No rule to make target '/home/jacos/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk'.  Stop.

```
the make file is there it just doesnt work  
and when trying to compile example-PoseNet 
 i get this:
```
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(DigestEngine.o):DigestEngine.cpp:function Poco::Crypto::DigestEngine::~DigestEngine(): error: undefined reference to 'EVP_MD_CTX_destroy'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(DigestEngine.o):DigestEngine.cpp:function Poco::Crypto::DigestEngine::reset(): error: undefined reference to 'EVP_MD_CTX_cleanup'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(DigestEngine.o):DigestEngine.cpp:function Poco::Crypto::DigestEngine::DigestEngine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&): error: undefined reference to 'EVP_MD_CTX_create'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'EVP_cleanup'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'ERR_free_strings'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'CRYPTO_set_locking_callback'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'CRYPTO_set_id_callback'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'SSL_library_init'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'SSL_load_error_strings'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'OPENSSL_add_all_algorithms_noconf'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_num_locks'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_locking_callback'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_id_callback'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_dynlock_create_callback'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_dynlock_lock_callback'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::initialize(): error: undefined reference to 'CRYPTO_set_dynlock_destroy_callback'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'CONF_modules_free'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoNetSSL.a(Context.o):Context.cpp:function Poco::Net::Context::createSSLContext(): error: undefined reference to 'SSLv23_client_method'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoNetSSL.a(Context.o):Context.cpp:function Poco::Net::Context::createSSLContext(): error: undefined reference to 'SSLv23_server_method'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/jacos/OF11/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:405: bin/example-PoseNet] Error 1
make[1]: Leaving directory '/home/jacos/OF11/addons/ofxRunway/example-PoseNet'
make: *** [/home/jacos/OF11/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2

```

**Comment by roymacdonald** [comment]
It seems that the problem then is related to PG properly generating the make files.
When you way that it works properly when copying the make file from some other example, which other example you mean? an ofxRunway example or a regular OF example?

**Comment by cyrstem** [comment]
@roymacdonald  ,  no  i copy the makefile from any other project  i made or used and it works, it just doesnt generate the makefile correctly on ofxRunway examples at least on linux

**Comment by roymacdonald** [comment]
Hi, this is kinda odd. Have you compared the generated and the copied makefiles?

**Comment by cyrstem** [comment]
hi, so i  updated ofxRunway and i getting a new issue when trying to compile  

```
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoCrypto.a(OpenSSLInitializer.o):OpenSSLInitializer.cpp:function Poco::Crypto::OpenSSLInitializer::uninitialize(): error: undefined reference to 'CONF_modules_free'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoNetSSL.a(Context.o):Context.cpp:function Poco::Net::Context::createSSLContext(): error: undefined reference to 'SSLv23_client_method'
/home/jacos/OF11/addons/ofxPoco/libs/poco/lib/linux64/libPocoNetSSL.a(Context.o):Context.cpp:function Poco::Net::Context::createSSLContext(): error: undefined reference to 'SSLv23_server_method'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/jacos/OF11/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:405: bin/example-PoseNet] Error 1
make[1]: Leaving directory '/home/jacos/OF11/addons/ofxRunway/example-PoseNet'
make: *** [/home/jacos/OF11/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2
```

**Comment by cyrstem** [comment]
> Hi, this is kinda odd. Have you compared the generated and the copied makefiles?
this is the one generated by PG that doesn't work 
```

`# Attempt to load a config.make file.
# If none is found, project defaults in config.project.make will be used.
ifneq ($(wildcard config.make),)
	include config.make
endif

# make sure the the OF_ROOT location is defined
ifndef OF_ROOT
	OF_ROOT=$(realpath ../../..)
endif

# call the project makefile!
include $(OF_ROOT)/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk
`
```

this one is the one i generate in other project and replace to make it compile on the ofxRunway examples
```
`# Attempt to load a config.make file.
# If none is found, project defaults in config.project.make will be used.
ifneq ($(wildcard config.make),)
	include config.make
endif

# make sure the the OF_ROOT location is defined
ifndef OF_ROOT
	OF_ROOT=$(realpath ../../..)
endif

# call the project makefile!
include $(OF_ROOT)/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk


`

```
the weird thing is that this make file error only happens with ofxRunway

**Comment by roymacdonald** [comment]
Hi. I can not see any difference between those two make files. It is really odd.
When you updated ofxRunway, did you updated 


> hi, so i updated ofxRunway and i getting a new issue when trying to compile
this might be related to that issue. https://github.com/bakercp/ofxSSLManager/issues/1
Also, it sounds like it is missing some symbols from the POCO library, which is included with OF.
Are you using the latest nightly build or github version? if you are using the github version it might be a good idea to run the update libraries `scripts/dev/download_libs.sh`
Another thing you can do is trying to compile and run the ofxHTTP examples? if these work then it is my fault, otherwise it is a problem on the addons on which ofxRunway depend.

**Comment by cyrstem** [comment]
i updated that same day  it seems like Poco is the issue as  i can compile any of the ofxHttp examples

**Comment by roymacdonald** [comment]
> Hi. I can not see any difference between those two make files. It is really odd.
When you updated ofxRunway, did you updated

Hi @cyrstem , sorry for my belated reply.

This is super odd. I really have no idea. I could try installing linux on a virtual machine and see what's going on. Which linux version are you using?

**Comment by cyrstem** [comment]
@roymacdonald  hey thanks ,im on manjaro  im gonna get the newest  nightly  today to see if that helps with the project manager issue, but any way i have try to compile the examples from ofxhttp  but none of them compile ill keep  trying  any way

**Comment by roymacdonald** [comment]
Hi, maybe @bakercp can give as a hand as on why it is not compiling on manjaro.
Let us know if you've made any improvements.

**Comment by tobyshooters** [comment]
Hey @roymacdonald,

I'm able to connect Runway to OpenFrameworks. However, when streaming data to PoseNet, I never get a response.

I have a VideoGrabber which I sample from once a second, and send the data to Runway. Then, I just get the poses.

Any suggestions?

```
#include "ofApp.h"

//--------------------------------------------------------------
void ofApp::setup(){
    ofSetFrameRate(25);
    ofSetWindowShape(640, 480);
    video.setup(640, 480);

    poseFeatures.setup(runway.getOutputTypes());
    runway.setup(this, "http://localhost:8000");
    runway.start();
}

//--------------------------------------------------------------
void ofApp::update(){
    video.update();

    if (ofGetFrameNum() % 25 == 0) {

        if (video.isFrameNew() && !runway.isBusy()) {
            cout << "SENT DATA" << endl;
            ofxRunwayData data;
            data.setImage("image", video.getPixels(),
                    OFX_RUNWAY_JPG, video.getWidth(), video.getHeight());
            data.setInt("estimationType", 0);
            data.setInt("maxPoseDetections", 1);
            data.setFloat("scoreThreshold", 0.3);

            runway.send(data);
        }

        runway.get(poses, video.getWidth(), video.getHeight(), OFX_RUNWAY_POSE_NET);
    }
}

//--------------------------------------------------------------
void ofApp::draw(){
    video.draw(0, 0);

    runway.drawStatus(0, 0, true);

    for (auto &p : poses) {
        p.draw(poseFeatures);
    }
}
```

**Comment by roymacdonald** [comment]
Hi @tobyshooters,  I remember seeing this issue a while back. I am not really sure what's going on. I suspect it could be because of it running locally. Let me double check if this is a problem related to the addon or to the runway app.

**Comment by roymacdonald** [comment]
@tobyshooters  I found the problem and updated. Please pull from the repo and try again. 
It was a nasty bug due to the base64 image compression.
